
package pe.edu.upeu.soap.ws.daoImpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import pe.edu.upeu.soap.ws.dao.ObjectFactory;
import pe.edu.upeu.soap.ws.dao.Reporte;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReporteDao", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReporteDao {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<pe.edu.upeu.soap.ws.dao.Reporte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarReporte", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/", className = "pe.edu.upeu.soap.ws.dao.GenerarReporte")
    @ResponseWrapper(localName = "generarReporteResponse", targetNamespace = "http://dao.ws.soap.upeu.edu.pe/", className = "pe.edu.upeu.soap.ws.dao.GenerarReporteResponse")
    @Action(input = "http://dao.ws.soap.upeu.edu.pe/ReporteDao/generarReporteRequest", output = "http://dao.ws.soap.upeu.edu.pe/ReporteDao/generarReporteResponse")
    public List<Reporte> generarReporte(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
