
package pe.edu.upeu.soap.ws.daoImpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReporteDaoImplService", targetNamespace = "http://daoImpl.ws.soap.upeu.edu.pe/", wsdlLocation = "http://localhost:5051/soap/cliente/reporte?wsdl")
public class ReporteDaoImplService
    extends Service
{

    private final static URL REPORTEDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPORTEDAOIMPLSERVICE_EXCEPTION;
    private final static QName REPORTEDAOIMPLSERVICE_QNAME = new QName("http://daoImpl.ws.soap.upeu.edu.pe/", "ReporteDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5051/soap/cliente/reporte?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTEDAOIMPLSERVICE_WSDL_LOCATION = url;
        REPORTEDAOIMPLSERVICE_EXCEPTION = e;
    }

    public ReporteDaoImplService() {
        super(__getWsdlLocation(), REPORTEDAOIMPLSERVICE_QNAME);
    }

    public ReporteDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTEDAOIMPLSERVICE_QNAME, features);
    }

    public ReporteDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, REPORTEDAOIMPLSERVICE_QNAME);
    }

    public ReporteDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTEDAOIMPLSERVICE_QNAME, features);
    }

    public ReporteDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReporteDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReporteDao
     */
    @WebEndpoint(name = "ReporteDaoImplPort")
    public ReporteDao getReporteDaoImplPort() {
        return super.getPort(new QName("http://daoImpl.ws.soap.upeu.edu.pe/", "ReporteDaoImplPort"), ReporteDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReporteDao
     */
    @WebEndpoint(name = "ReporteDaoImplPort")
    public ReporteDao getReporteDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://daoImpl.ws.soap.upeu.edu.pe/", "ReporteDaoImplPort"), ReporteDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTEDAOIMPLSERVICE_EXCEPTION!= null) {
            throw REPORTEDAOIMPLSERVICE_EXCEPTION;
        }
        return REPORTEDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
